# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20150902_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('ports', models.CharField(blank=True, max_length=500, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('in_use', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('used_time', models.DateTimeField(blank=True, null=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'endpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'providers',
                'managed': False,
            },
        ),
    ]
