---
- name: install vmmaster_frontend | apply special settings.py in vmmaster_frontend directory
  template: src={{vmmaster_frontend_settings_name}} dest={{vmmaster_frontend_path}}/vmmaster_frontend/settings.py mode=0644

- name:
  file: path={{item.path}} owner=vmmaster group=vmmaster mode={{item.mod}} state={{item.state}}
  with_items:
    - {path: "{{vmmaster_frontend_path}}/api", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/dashboard", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/session", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/static", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/templates", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/users", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/vmmaster_frontend", state: "directory", mod: "0775"}
    - {path: "{{vmmaster_frontend_path}}/manage.py", state: "file", mod: "0644"}

- name: install vmmaster_frontend | apply migrations
  shell: sudo -u vmmaster python {{vmmaster_frontend_path}}/manage.py migrate --noinput

- name: install vmmaster_frontend | collect static files
  shell: sudo -u vmmaster python {{vmmaster_frontend_path}}/manage.py collectstatic --noinput
