---
- name: install vmmaster_frontend | Clone repo
  git: repo=git://github.com/2gis/vmmaster-frontend.git
       dest={{vmmaster_frontend_path}}/vmmaster-frontend-new
       version={{branch}}
       accept_hostkey=True

- name: install vmmaster_frontend | Apply django settings.py
  template: src={{vmmaster_frontend_settings_name}} dest={{vmmaster_frontend_path}}/vmmaster-frontend-new/vmmaster_frontend/settings.py mode=0644

#

- name: install vmmaster_frontend | Stop service
  shell: sudo service vmmaster-frontend stop
  when: restart_service

#

- name: install vmmaster_frontend | Delete old backup version
  file: path={{vmmaster_frontend_path}}/vmmaster-frontend-old state=absent

- name: install vmmaster_frontend | Replace old by current
  shell: sudo mv {{vmmaster_frontend_path}}/vmmaster-frontend-current {{vmmaster_frontend_path}}/vmmaster-frontend-old

- name: install vmmaster_frontend | Replace current by new version
  shell: sudo mv {{vmmaster_frontend_path}}/vmmaster-frontend-new {{vmmaster_frontend_path}}/vmmaster-frontend-current

#

- copy: src={{vmmaster_frontend_path}}/vmmaster-frontend-old/vmmaster-frontend.conf dest={{vmmaster_frontend_path}}/vmmaster-frontend/foo.conf owner=vmmaster group=vmmaster mode=0644

- copy: src={{vmmaster_frontend_path}}/vmmaster-frontend-old/vmmaster-frontend.ini dest={{vmmaster_frontend_path}}/vmmaster-frontend/foo.ini owner=vmmaster group=vmmaster mode=0644

#

- name: install vmmaster_frontend | Chmod
  shell: sudo chown -R vmmaster:vmmaster {{vmmaster_frontend_path}}/*

- name: install vmmaster_frontend | Apply Django migrations
  shell: sudo -u vmmaster python {{vmmaster_frontend_path}}/vmmaster-frontend/manage.py migrate --noinput

- name: install vmmaster_frontend | Collect static files
  shell: sudo -u vmmaster python {{vmmaster_frontend_path}}/vmmaster-frontend/manage.py collectstatic --noinput

#

- name: install vmmaster_frontend | Start service
  shell: sudo service vmmaster-frontend start
  when: restart_service